import { ReduxProvider } from '@/redux/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/Sidebar'
import Topbar from './components/Topbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-purple-700">
        <ReduxProvider>
          <div className=' min-h-screen'>
            <div className=' bg-pink-600 flex flex-col'>
             <Topbar />
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
