import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topbar from './components/Topbar'
import Sidebar from './components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-purple-700">
        <div className='flex min-h-screen'>
          <Sidebar />
          <div className='flex-1 bg-pink-600'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
